DROP TABLE IF EXISTS TBL_EMPLOYEES;

CREATE TABLE PERSONS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  phone_no VARCHAR(10) DEFAULT NULL
);